export {
  DOMAIN_OWNERSHIP_SCHEMA_DEF,
  DOMAIN_OWNERSHIP_SCHEMA_NAME,
  DOMAIN_OWNERSHIP_METHOD,
  createDomainOwnershipChallenge,
  verifyDomainOwnershipDns,
  lookupDomainRegistry,
  normalizeRegistrableDomain,
  fingerprintFromRegistrySnapshot,
  getDomainOwnershipSchemaUid,
  ensureDomainOwnershipSchema,
  encodeDomainOwnershipAttestationData,
  attestDomainOwnership,
  revokeDomainOwnership,
  verifyDomainOwnershipChallenge,
  verifyAndAttestDomainOwnership,
  assessDomainOwnershipLive,
  type DomainOwnershipChallenge,
  type DomainRegistrySnapshot,
  type VerifyDomainOwnershipDnsResult,
  type AttestDomainOwnershipParams,
  type AttestDomainOwnershipResult,
  type VerifyDomainOwnershipChallengeResult,
  type VerifyAndAttestDomainOwnershipResult,
  type AssessDomainOwnershipLiveResult,
} from './index'
