// This file is auto-generated by generate-fixture-files.ts
// Do not edit manually - run the generator script to update
//
// This file embeds fixture files as strings for browser runtime
// These files are copied from __tests__/__fixtures__ at build time

export const fixture_schema_with_ids_json = `{
  "$schema": "https://seedprotocol.org/schemas/data-model/v1",
  "version": 1,
  "id": "TEST_SCHEMA_WITH_IDS",
  "metadata": {
    "name": "Test Schema With IDs",
    "description": "A test schema with all IDs provided",
    "createdAt": "2025-01-01T00:00:00Z",
    "updatedAt": "2025-01-01T00:00:00Z"
  },
  "models": {
    "User": {
      "id": "TEST_USER_MODEL",
      "description": "A user model with all IDs",
      "properties": {
        "name": {
          "id": "TEST_USER_NAME_PROP",
          "type": "Text"
        },
        "email": {
          "id": "TEST_USER_EMAIL_PROP",
          "type": "Text"
        },
        "age": {
          "id": "TEST_USER_AGE_PROP",
          "type": "Number"
        }
      }
    },
    "Post": {
      "id": "TEST_POST_MODEL",
      "description": "A post model with all IDs",
      "properties": {
        "title": {
          "id": "TEST_POST_TITLE_PROP",
          "type": "Text"
        },
        "content": {
          "id": "TEST_POST_CONTENT_PROP",
          "type": "Text"
        },
        "author": {
          "id": "TEST_POST_AUTHOR_PROP",
          "type": "Relation",
          "model": "User"
        }
      }
    }
  },
  "enums": {},
  "migrations": [
    {
      "version": 1,
      "timestamp": "2025-01-01T00:00:00Z",
      "description": "Initial schema with all IDs",
      "changes": []
    }
  ]
}`

export const fixture_schema_without_ids_json = `{
  "$schema": "https://seedprotocol.org/schemas/data-model/v1",
  "version": 1,
  "metadata": {
    "name": "Test Schema Without IDs",
    "description": "A test schema without any IDs - should generate them",
    "createdAt": "2025-01-01T00:00:00Z",
    "updatedAt": "2025-01-01T00:00:00Z"
  },
  "models": {
    "Product": {
      "description": "A product model without IDs",
      "properties": {
        "name": {
          "type": "Text"
        },
        "price": {
          "type": "Number"
        },
        "description": {
          "type": "Text"
        }
      }
    },
    "Category": {
      "description": "A category model without IDs",
      "properties": {
        "name": {
          "type": "Text"
        },
        "slug": {
          "type": "Text"
        }
      }
    }
  },
  "enums": {},
  "migrations": [
    {
      "version": 1,
      "timestamp": "2025-01-01T00:00:00Z",
      "description": "Initial schema without IDs",
      "changes": []
    }
  ]
}`

export const fixture_schema_partial_ids_json = `{
  "$schema": "https://seedprotocol.org/schemas/data-model/v1",
  "version": 1,
  "id": "TEST_SCHEMA_PARTIAL",
  "metadata": {
    "name": "Test Schema With Partial IDs",
    "description": "A test schema with some IDs missing - should generate missing ones",
    "createdAt": "2025-01-01T00:00:00Z",
    "updatedAt": "2025-01-01T00:00:00Z"
  },
  "models": {
    "Order": {
      "id": "TEST_ORDER_MODEL",
      "description": "Order model with ID",
      "properties": {
        "orderNumber": {
          "id": "TEST_ORDER_NUMBER_PROP",
          "type": "Text"
        },
        "total": {
          "type": "Number"
        },
        "status": {
          "type": "Text"
        }
      }
    },
    "Item": {
      "description": "Item model without ID",
      "properties": {
        "name": {
          "id": "TEST_ITEM_NAME_PROP",
          "type": "Text"
        },
        "quantity": {
          "type": "Number"
        },
        "price": {
          "type": "Number"
        }
      }
    }
  },
  "enums": {},
  "migrations": [
    {
      "version": 1,
      "timestamp": "2025-01-01T00:00:00Z",
      "description": "Initial schema with partial IDs",
      "changes": []
    }
  ]
}`

// Map fixture names to their content
export const fixtureFiles: Record<string, string> = {
  'schema-with-ids.json': fixture_schema_with_ids_json,
  'schema-without-ids.json': fixture_schema_without_ids_json,
  'schema-partial-ids.json': fixture_schema_partial_ids_json,
}

