#!/usr/bin/env bun
/**
 * Script to generate fixtureFiles.ts from __tests__/__fixtures__ directory
 * 
 * This script reads all files from __tests__/__fixtures__ and generates
 * a TypeScript file with exported string constants for browser bundling.
 * 
 * Usage: bun run __tests__/test-utils/generate-fixture-files.ts
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// Paths
const fixturesDir = path.join(__dirname, '..', '__fixtures__')
const outputFile = path.join(__dirname, 'fixtureFiles.ts')

/**
 * Convert a filename to a valid TypeScript variable name
 */
function toVariableName(filename: string): string {
  // Remove extension and replace non-alphanumeric chars with underscore
  const baseName = filename.replace(/\.[^/.]+$/, '')
  return `fixture_${baseName.replace(/[^a-zA-Z0-9]/g, '_')}`
}

/**
 * Escape a string for use in a TypeScript template literal
 */
function escapeString(content: string): string {
  // For template literals, we need to escape backticks, ${, and \
  return content
    .replace(/\\/g, '\\\\')  // Escape backslashes first
    .replace(/`/g, '\\`')    // Escape backticks
    .replace(/\${/g, '\\${') // Escape ${ to prevent template interpolation
}

/**
 * Generate the fixtureFiles.ts file
 */
function generateFixtureFiles(): void {
  console.log(`Reading fixtures from: ${fixturesDir}`)
  
  if (!fs.existsSync(fixturesDir)) {
    throw new Error(`Fixtures directory not found: ${fixturesDir}`)
  }
  
  // Read all files from fixtures directory
  const files = fs.readdirSync(fixturesDir)
    .filter(file => {
      // Only include files (not directories)
      const filePath = path.join(fixturesDir, file)
      return fs.statSync(filePath).isFile()
    })
    .sort() // Sort for consistent output
  
  if (files.length === 0) {
    throw new Error(`No files found in fixtures directory: ${fixturesDir}`)
  }
  
  console.log(`Found ${files.length} fixture files`)
  
  // Generate TypeScript file content
  const lines: string[] = []
  
  // Header
  lines.push('// This file is auto-generated by generate-fixture-files.ts')
  lines.push('// Do not edit manually - run the generator script to update')
  lines.push('//')
  lines.push('// This file embeds fixture files as strings for browser runtime')
  lines.push('// These files are copied from __tests__/__fixtures__ at build time')
  lines.push('')
  
  // Export each fixture as a constant
  const fixtureMap: Record<string, string> = {}
  
  for (const file of files) {
    const filePath = path.join(fixturesDir, file)
    const content = fs.readFileSync(filePath, 'utf-8')
    const varName = toVariableName(file)
    
    // Store mapping
    fixtureMap[file] = varName
    
    // Export the constant
    lines.push(`export const ${varName} = \`${escapeString(content)}\``)
    lines.push('')
  }
  
  // Export the mapping object
  lines.push('// Map fixture names to their content')
  lines.push('export const fixtureFiles: Record<string, string> = {')
  for (const [filename, varName] of Object.entries(fixtureMap)) {
    lines.push(`  '${filename}': ${varName},`)
  }
  lines.push('}')
  lines.push('')
  
  // Write the file
  const output = lines.join('\n')
  fs.writeFileSync(outputFile, output, 'utf-8')
  
  console.log(`✓ Generated ${outputFile}`)
  console.log(`✓ Exported ${files.length} fixture files`)
  console.log(`✓ Total size: ${(output.length / 1024).toFixed(2)} KB`)
}

// Run the generator
try {
  generateFixtureFiles()
  console.log('✓ Done!')
  process.exit(0)
} catch (error) {
  console.error('✗ Error generating fixture files:', error)
  process.exit(1)
}

