import { Static } from '@sinclair/typebox';
import { PropertyDataType, PropertyDefs, StorageType } from '@/types';
/**
 * Enum for all property data types
 */
export declare enum ModelPropertyDataTypes {
    Text = "Text",
    Number = "Number",
    List = "List",
    Relation = "Relation",
    Image = "Image",
    Json = "Json",
    File = "File",
    Boolean = "Boolean",
    Date = "Date",
    Html = "Html"
}
/**
 * Normalize dataType to canonical PascalCase form.
 * Accepts lowercase (e.g. 'text') or mixed case and returns 'Text'.
 * Use when ingesting dataType from JSON schema files.
 */
export declare function normalizeDataType(value: string | undefined): string;
export declare const TPropertyDataType: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>;
export declare const TStorageType: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>;
export declare const TProperty: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    _dbId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    dataType: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>;
    ref: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    modelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TString]>>;
    modelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    refModelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    refModelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    refValueType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>>;
    storageType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>>;
    localStorageDir: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    filenameSuffix: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    validation: import("@sinclair/typebox").TOptionalFromMappedResult<any, true>;
}>;
export declare const TPropertyConstructor: import("@sinclair/typebox").TFunction<[import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>, import("@sinclair/typebox").TUndefined]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>], import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    _dbId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    dataType: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>;
    ref: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    modelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TString]>>;
    modelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    refModelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    refModelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    refValueType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>>;
    storageType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>>;
    localStorageDir: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    filenameSuffix: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    validation: import("@sinclair/typebox").TOptionalFromMappedResult<any, true>;
}>>;
export declare const TPropertyDefs: import("@sinclair/typebox").TObject<{
    Text: import("@sinclair/typebox").TFunction<[import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>, import("@sinclair/typebox").TUndefined]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>], import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        _dbId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        dataType: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>;
        ref: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        modelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TString]>>;
        modelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refModelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        refModelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refValueType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>>;
        storageType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>>;
        localStorageDir: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        filenameSuffix: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        validation: import("@sinclair/typebox").TOptionalFromMappedResult<any, true>;
    }>>;
    Number: import("@sinclair/typebox").TFunction<[import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>, import("@sinclair/typebox").TUndefined]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>], import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        _dbId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        dataType: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>;
        ref: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        modelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TString]>>;
        modelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refModelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        refModelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refValueType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>>;
        storageType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>>;
        localStorageDir: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        filenameSuffix: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        validation: import("@sinclair/typebox").TOptionalFromMappedResult<any, true>;
    }>>;
    List: import("@sinclair/typebox").TFunction<[import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>, import("@sinclair/typebox").TUndefined]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>], import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        _dbId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        dataType: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>;
        ref: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        modelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TString]>>;
        modelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refModelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        refModelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refValueType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>>;
        storageType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>>;
        localStorageDir: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        filenameSuffix: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        validation: import("@sinclair/typebox").TOptionalFromMappedResult<any, true>;
    }>>;
    Relation: import("@sinclair/typebox").TFunction<[import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>, import("@sinclair/typebox").TUndefined]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>], import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        _dbId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        dataType: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>;
        ref: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        modelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TString]>>;
        modelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refModelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        refModelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refValueType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>>;
        storageType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>>;
        localStorageDir: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        filenameSuffix: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        validation: import("@sinclair/typebox").TOptionalFromMappedResult<any, true>;
    }>>;
    Image: import("@sinclair/typebox").TFunction<[import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>, import("@sinclair/typebox").TUndefined]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>], import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        _dbId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        dataType: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>;
        ref: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        modelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TString]>>;
        modelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refModelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        refModelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refValueType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>>;
        storageType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>>;
        localStorageDir: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        filenameSuffix: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        validation: import("@sinclair/typebox").TOptionalFromMappedResult<any, true>;
    }>>;
    Json: import("@sinclair/typebox").TFunction<[import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>, import("@sinclair/typebox").TUndefined]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>], import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        _dbId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        dataType: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>;
        ref: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        modelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TString]>>;
        modelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refModelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        refModelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refValueType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>>;
        storageType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>>;
        localStorageDir: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        filenameSuffix: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        validation: import("@sinclair/typebox").TOptionalFromMappedResult<any, true>;
    }>>;
    File: import("@sinclair/typebox").TFunction<[import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>, import("@sinclair/typebox").TUndefined]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>], import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        _dbId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        dataType: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>;
        ref: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        modelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TString]>>;
        modelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refModelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        refModelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refValueType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>>;
        storageType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>>;
        localStorageDir: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        filenameSuffix: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        validation: import("@sinclair/typebox").TOptionalFromMappedResult<any, true>;
    }>>;
    Boolean: import("@sinclair/typebox").TFunction<[import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>, import("@sinclair/typebox").TUndefined]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>], import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        _dbId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        dataType: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>;
        ref: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        modelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TString]>>;
        modelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refModelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        refModelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refValueType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>>;
        storageType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>>;
        localStorageDir: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        filenameSuffix: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        validation: import("@sinclair/typebox").TOptionalFromMappedResult<any, true>;
    }>>;
    Date: import("@sinclair/typebox").TFunction<[import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>, import("@sinclair/typebox").TUndefined]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>], import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        _dbId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        dataType: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>;
        ref: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        modelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TString]>>;
        modelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refModelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        refModelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refValueType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>>;
        storageType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>>;
        localStorageDir: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        filenameSuffix: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        validation: import("@sinclair/typebox").TOptionalFromMappedResult<any, true>;
    }>>;
    Html: import("@sinclair/typebox").TFunction<[import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>, import("@sinclair/typebox").TUndefined]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>]>>, import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>], import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        _dbId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        dataType: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>;
        ref: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        modelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TString]>>;
        modelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refModelId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        refModelName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        refValueType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Text>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Number>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.List>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Relation>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Image>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Json>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.File>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Boolean>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Date>, import("@sinclair/typebox").TLiteral<ModelPropertyDataTypes.Html>]>>;
        storageType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"ItemStorage">, import("@sinclair/typebox").TLiteral<"PropertyStorage">]>>;
        localStorageDir: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        filenameSuffix: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        validation: import("@sinclair/typebox").TOptionalFromMappedResult<any, true>;
    }>>;
}>;
export declare const Property: PropertyDefs;
export declare const PropertyMetadataKey: unique symbol;
export declare const PropertyConstructor: (propertyType: Static<typeof TProperty>) => (parentClassPrototype: any, propertyKey: string) => void;
export declare const Text: (storageType?: StorageType, srcDir?: string, filenameSuffix?: string) => (parentClassPrototype: any, propertyKey: string) => void;
export declare const Number: () => (parentClassPrototype: any, propertyKey: string) => void;
export declare const Json: () => (parentClassPrototype: any, propertyKey: string) => void;
export declare const File: () => (parentClassPrototype: any, propertyKey: string) => void;
export declare const Image: () => (parentClassPrototype: any, propertyKey: string) => void;
export declare const Relation: (ref: string, refValueType?: PropertyDataType) => (parentClassPrototype: any, propertyKey: string) => void;
export declare const List: (refValueType: PropertyDataType, ref?: string) => (parentClassPrototype: any, propertyKey: string) => void;
export declare const Boolean: () => (parentClassPrototype: any, propertyKey: string) => void;
export declare const Date: () => (parentClassPrototype: any, propertyKey: string) => void;
//# sourceMappingURL=index.d.ts.map